#!/bin/bash
xrandr --output HDMI-0 --mode 1920x1080 --primary --output DP-0 --mode 1280x1024 --right-of HDMI-0
# xrandr --output HDMI-A-0 --mode 1920x1080 --primary --output DisplayPort-0 --mode 1280x1024 --right-of HDMI-A-0
